#!/bin/bash
# GTK3 Theme Generator - Generate GTK3 CSS from Omarchy color scheme

THEME_DIR="$1"

if [ -z "$THEME_DIR" ] || [ ! -d "$THEME_DIR" ]; then
    echo "Error: Invalid theme directory"
    exit 1
fi

# Check if colors.conf exists
if [ ! -f "$THEME_DIR/colors.conf" ]; then
    echo "Error: colors.conf not found in theme directory"
    exit 1
fi

# Load colors
source "$THEME_DIR/colors.conf"

THEME_NAME=$(basename "$THEME_DIR")
GTK_THEME_DIR="$HOME/.themes/$THEME_NAME"
mkdir -p "$GTK_THEME_DIR/gtk-3.0"

notify-send "Generating GTK3 Theme" "Creating GTK3 theme for $THEME_NAME..."

# Generate GTK3 CSS
cat > "$GTK_THEME_DIR/gtk-3.0/gtk.css" << EOF
/* GTK3 Theme: $THEME_NAME */
/* Auto-generated by Omarchy Theme System */

/* Color Definitions */
@define-color theme_bg_color $background;
@define-color theme_fg_color $foreground;
@define-color theme_base_color $background;
@define-color theme_text_color $foreground;
@define-color theme_selected_bg_color $color4;
@define-color theme_selected_fg_color $background;
@define-color insensitive_bg_color mix($background, $foreground, 0.9);
@define-color insensitive_fg_color mix($foreground, $background, 0.5);
@define-color borders mix($foreground, $background, 0.8);
@define-color warning_color $color3;
@define-color error_color $color1;
@define-color success_color $color2;

/* Window */
window {
    background-color: @theme_bg_color;
    color: @theme_fg_color;
}

/* Headers */
headerbar {
    background-color: mix($background, $foreground, 0.95);
    color: @theme_fg_color;
    border-bottom: 1px solid @borders;
    padding: 6px;
}

headerbar:backdrop {
    background-color: @theme_bg_color;
}

/* Buttons */
button {
    background-color: mix($background, $foreground, 0.9);
    color: @theme_fg_color;
    border: 1px solid @borders;
    border-radius: 6px;
    padding: 6px 12px;
    transition: all 200ms ease;
}

button:hover {
    background-color: mix($background, $color4, 0.85);
    border-color: $color4;
}

button:active {
    background-color: $color4;
    color: $background;
}

button:disabled {
    background-color: @insensitive_bg_color;
    color: @insensitive_fg_color;
}

button.suggested-action {
    background-color: $color4;
    color: $background;
}

button.destructive-action {
    background-color: $color1;
    color: $background;
}

/* Entries */
entry {
    background-color: mix($background, $foreground, 0.95);
    color: @theme_fg_color;
    border: 1px solid @borders;
    border-radius: 6px;
    padding: 6px;
}

entry:focus {
    border-color: $color4;
    box-shadow: 0 0 0 2px alpha($color4, 0.2);
}

/* Selections */
selection {
    background-color: $color4;
    color: $background;
}

/* Scrollbars */
scrollbar {
    background-color: transparent;
}

scrollbar slider {
    background-color: mix($foreground, $background, 0.3);
    border-radius: 10px;
    min-width: 8px;
    min-height: 8px;
}

scrollbar slider:hover {
    background-color: mix($foreground, $background, 0.4);
}

scrollbar slider:active {
    background-color: $color4;
}

/* Checkboxes and Radio Buttons */
check, radio {
    background-color: mix($background, $foreground, 0.9);
    border: 1px solid @borders;
    border-radius: 3px;
    min-width: 16px;
    min-height: 16px;
}

check:checked, radio:checked {
    background-color: $color4;
    border-color: $color4;
    color: $background;
}

/* Switches */
switch {
    background-color: mix($background, $foreground, 0.8);
    border-radius: 12px;
}

switch:checked {
    background-color: $color4;
}

switch slider {
    background-color: $foreground;
    border-radius: 50%;
}

/* Menus */
menu {
    background-color: mix($background, $foreground, 0.95);
    color: @theme_fg_color;
    border: 1px solid @borders;
    border-radius: 8px;
    padding: 4px;
}

menuitem {
    border-radius: 4px;
    padding: 6px;
}

menuitem:hover {
    background-color: $color4;
    color: $background;
}

/* Popovers */
popover {
    background-color: mix($background, $foreground, 0.95);
    color: @theme_fg_color;
    border: 1px solid @borders;
    border-radius: 8px;
    padding: 8px;
}

/* Tooltips */
tooltip {
    background-color: mix($background, $foreground, 0.1);
    color: @theme_fg_color;
    border-radius: 6px;
    padding: 6px 10px;
}

/* Sidebars */
sidebar {
    background-color: mix($background, $foreground, 0.97);
    border-right: 1px solid @borders;
}

sidebar row:selected {
    background-color: $color4;
    color: $background;
}

/* Notebook tabs */
notebook {
    background-color: @theme_bg_color;
}

notebook header {
    background-color: mix($background, $foreground, 0.95);
}

notebook tab {
    background-color: transparent;
    padding: 6px 12px;
    border-radius: 6px 6px 0 0;
}

notebook tab:checked {
    background-color: @theme_bg_color;
}

/* Progress bars */
progressbar trough {
    background-color: mix($background, $foreground, 0.9);
    border-radius: 6px;
}

progressbar progress {
    background-color: $color4;
    border-radius: 6px;
}

/* Lists */
list {
    background-color: @theme_base_color;
    color: @theme_text_color;
}

list row:selected {
    background-color: $color4;
    color: $background;
}

list row:hover {
    background-color: mix($background, $color4, 0.9);
}

/* Separators */
separator {
    background-color: @borders;
    min-width: 1px;
    min-height: 1px;
}

/* Spinners */
spinner {
    color: $color4;
}

/* Scale (sliders) */
scale trough {
    background-color: mix($background, $foreground, 0.9);
    border-radius: 6px;
}

scale highlight {
    background-color: $color4;
    border-radius: 6px;
}

scale slider {
    background-color: $foreground;
    border: 2px solid $color4;
    border-radius: 50%;
    min-width: 16px;
    min-height: 16px;
}

/* Statusbar */
statusbar {
    background-color: mix($background, $foreground, 0.95);
    padding: 4px;
}

/* Info/Warning/Error bars */
.info {
    background-color: $color4;
    color: $background;
}

.warning {
    background-color: $color3;
    color: $background;
}

.error {
    background-color: $color1;
    color: $background;
}

.success {
    background-color: $color2;
    color: $background;
}
EOF

notify-send "✓ GTK3 Theme Generated" "Theme installed at: $GTK_THEME_DIR"
echo "$GTK_THEME_DIR/gtk-3.0/gtk.css"
