#!/bin/bash
# GTK4 Theme Generator - Generate GTK4 CSS from Omarchy color scheme

THEME_DIR="$1"

if [ -z "$THEME_DIR" ] || [ ! -d "$THEME_DIR" ]; then
    echo "Error: Invalid theme directory"
    exit 1
fi

# Check if colors.conf exists
if [ ! -f "$THEME_DIR/colors.conf" ]; then
    echo "Error: colors.conf not found in theme directory"
    exit 1
fi

# Load colors
source "$THEME_DIR/colors.conf"

THEME_NAME=$(basename "$THEME_DIR")
GTK4_CONFIG_DIR="$HOME/.config/gtk-4.0"
mkdir -p "$GTK4_CONFIG_DIR"

notify-send "Generating GTK4 Theme" "Creating GTK4 theme for $THEME_NAME..."

# Generate GTK4 CSS
cat > "$GTK4_CONFIG_DIR/gtk.css" << EOF
/* GTK4 Theme: $THEME_NAME */
/* Auto-generated by Omarchy Theme System */

/* Color Definitions */
@define-color window_bg_color $background;
@define-color window_fg_color $foreground;
@define-color view_bg_color $background;
@define-color view_fg_color $foreground;
@define-color headerbar_bg_color mix($background, $foreground, 0.95);
@define-color headerbar_fg_color $foreground;
@define-color card_bg_color mix($background, $foreground, 0.95);
@define-color card_fg_color $foreground;
@define-color dialog_bg_color $background;
@define-color dialog_fg_color $foreground;
@define-color popover_bg_color mix($background, $foreground, 0.95);
@define-color popover_fg_color $foreground;
@define-color accent_bg_color $color4;
@define-color accent_fg_color $background;
@define-color accent_color $color4;
@define-color destructive_bg_color $color1;
@define-color destructive_fg_color $background;
@define-color destructive_color $color1;
@define-color success_bg_color $color2;
@define-color success_fg_color $background;
@define-color success_color $color2;
@define-color warning_bg_color $color3;
@define-color warning_fg_color $background;
@define-color warning_color $color3;
@define-color error_bg_color $color1;
@define-color error_fg_color $background;
@define-color error_color $color1;
@define-color sidebar_bg_color mix($background, $foreground, 0.97);
@define-color sidebar_fg_color $foreground;
@define-color shade_color alpha($foreground, 0.1);
@define-color scrollbar_outline_color alpha($foreground, 0.2);

/* Base styles */
window {
    background-color: @window_bg_color;
    color: @window_fg_color;
}

/* Headers */
headerbar {
    background-color: @headerbar_bg_color;
    color: @headerbar_fg_color;
    border-bottom: 1px solid alpha(@window_fg_color, 0.1);
    box-shadow: 0 1px 3px alpha(@shade_color, 0.2);
}

/* Buttons */
button {
    background-color: mix($background, $foreground, 0.9);
    color: @window_fg_color;
    border: 1px solid alpha(@window_fg_color, 0.2);
    border-radius: 8px;
    padding: 8px 16px;
    transition: all 200ms cubic-bezier(0.25, 0.46, 0.45, 0.94);
}

button:hover {
    background-color: mix($background, $color4, 0.85);
    border-color: alpha(@accent_color, 0.4);
}

button:active {
    background-color: @accent_bg_color;
    color: @accent_fg_color;
}

button:disabled {
    opacity: 0.5;
}

button.suggested-action {
    background-color: @accent_bg_color;
    color: @accent_fg_color;
}

button.destructive-action {
    background-color: @destructive_bg_color;
    color: @destructive_fg_color;
}

/* Entries */
entry {
    background-color: mix($background, $foreground, 0.95);
    color: @window_fg_color;
    border: 1px solid alpha(@window_fg_color, 0.2);
    border-radius: 8px;
    padding: 8px;
    transition: border 200ms;
}

entry:focus-within {
    border-color: @accent_color;
    box-shadow: inset 0 0 0 1px @accent_color;
}

/* Checkboxes */
checkbutton check {
    background-color: mix($background, $foreground, 0.9);
    border: 1px solid alpha(@window_fg_color, 0.2);
    border-radius: 4px;
    min-width: 18px;
    min-height: 18px;
}

checkbutton:checked check {
    background-color: @accent_bg_color;
    border-color: @accent_bg_color;
    color: @accent_fg_color;
}

/* Switches */
switch {
    background-color: mix($background, $foreground, 0.8);
    border-radius: 14px;
    min-width: 44px;
    min-height: 24px;
}

switch:checked {
    background-color: @accent_bg_color;
}

switch slider {
    background-color: $foreground;
    border-radius: 50%;
    min-width: 20px;
    min-height: 20px;
}

/* Scrollbars */
scrollbar {
    background-color: transparent;
}

scrollbar slider {
    background-color: alpha($foreground, 0.3);
    border-radius: 12px;
    min-width: 10px;
    min-height: 10px;
    margin: 2px;
}

scrollbar slider:hover {
    background-color: alpha($foreground, 0.4);
}

scrollbar slider:active {
    background-color: @accent_color;
}

/* Popovers */
popover {
    background-color: @popover_bg_color;
    color: @popover_fg_color;
    border: 1px solid alpha(@window_fg_color, 0.1);
    border-radius: 12px;
    box-shadow: 0 2px 8px alpha(@shade_color, 0.4);
    padding: 8px;
}

popover > contents {
    padding: 8px;
}

/* Menus */
popover.menu {
    padding: 4px;
}

popover.menu menuitem {
    border-radius: 6px;
    padding: 8px;
}

popover.menu menuitem:hover {
    background-color: @accent_bg_color;
    color: @accent_fg_color;
}

/* Lists */
listview {
    background-color: @view_bg_color;
    color: @view_fg_color;
}

listview row {
    border-radius: 6px;
    margin: 2px 4px;
}

listview row:hover {
    background-color: mix($background, $color4, 0.9);
}

listview row:selected {
    background-color: @accent_bg_color;
    color: @accent_fg_color;
}

/* Sidebars */
.sidebar {
    background-color: @sidebar_bg_color;
}

.sidebar row {
    border-radius: 6px;
    margin: 2px 4px;
}

.sidebar row:selected {
    background-color: @accent_bg_color;
    color: @accent_fg_color;
}

/* Cards */
.card {
    background-color: @card_bg_color;
    color: @card_fg_color;
    border-radius: 12px;
    box-shadow: 0 1px 3px alpha(@shade_color, 0.3);
}

/* Notebook tabs */
notebook {
    background-color: @window_bg_color;
}

notebook > header {
    background-color: @headerbar_bg_color;
}

notebook > header > tabs > tab {
    background-color: transparent;
    border-radius: 8px 8px 0 0;
    padding: 8px 16px;
}

notebook > header > tabs > tab:checked {
    background-color: @window_bg_color;
    box-shadow: 0 -2px 0 @accent_color inset;
}

/* Progress bars */
progressbar trough {
    background-color: mix($background, $foreground, 0.9);
    border-radius: 8px;
}

progressbar progress {
    background-color: @accent_bg_color;
    border-radius: 8px;
}

/* Scale (sliders) */
scale trough {
    background-color: mix($background, $foreground, 0.9);
    border-radius: 8px;
}

scale highlight {
    background-color: @accent_bg_color;
    border-radius: 8px;
}

scale slider {
    background-color: $foreground;
    border: 2px solid @accent_color;
    border-radius: 50%;
    min-width: 18px;
    min-height: 18px;
}

/* Tooltips */
tooltip {
    background-color: mix($background, $foreground, 0.1);
    color: @window_fg_color;
    border-radius: 8px;
    box-shadow: 0 2px 6px alpha(@shade_color, 0.4);
    padding: 8px 12px;
}

/* Separators */
separator {
    background-color: alpha(@window_fg_color, 0.1);
    min-width: 1px;
    min-height: 1px;
}

/* Message dialogs */
.dialog-action-area {
    padding: 12px;
}

.message-dialog .dialog-vbox {
    padding: 24px;
}

/* Info/Warning/Error styles */
.info {
    background-color: @accent_bg_color;
    color: @accent_fg_color;
}

.warning {
    background-color: @warning_bg_color;
    color: @warning_fg_color;
}

.error {
    background-color: @error_bg_color;
    color: @error_fg_color;
}

.success {
    background-color: @success_bg_color;
    color: @success_fg_color;
}

/* Spinners */
spinner {
    color: @accent_color;
}

/* Level bar */
levelbar trough {
    background-color: mix($background, $foreground, 0.9);
    border-radius: 8px;
}

levelbar block.filled {
    background-color: @accent_bg_color;
    border-radius: 8px;
}

levelbar block.empty {
    background-color: transparent;
}
EOF

notify-send "✓ GTK4 Theme Generated" "Theme applied to: $GTK4_CONFIG_DIR/gtk.css"
echo "$GTK4_CONFIG_DIR/gtk.css"
