#!/bin/bash
# Generate Config Files - Create all config files from color values

THEME_DIR="$1"
COLORS_FILE="$THEME_DIR/colors.conf"

if [ ! -f "$COLORS_FILE" ]; then
    echo "Error: Colors file not found: $COLORS_FILE"
    exit 1
fi

# Source the colors
source "$COLORS_FILE"

notify-send "Generating Configs" "Creating theme configuration files..."

# 1. Generate Alacritty config
cat > "$THEME_DIR/alacritty.toml" << EOF
# Alacritty Color Scheme
# Generated by Omarchy Theme Editor

[colors.primary]
background = "$background"
foreground = "$foreground"

[colors.normal]
black   = "$color0"
red     = "$color1"
green   = "$color2"
yellow  = "$color3"
blue    = "$color4"
magenta = "$color5"
cyan    = "$color6"
white   = "$color7"

[colors.bright]
black   = "$color8"
red     = "$color9"
green   = "$color10"
yellow  = "$color11"
blue    = "$color12"
magenta = "$color13"
cyan    = "$color14"
white   = "$color15"
EOF

# 2. Generate Hyprland config
cat > "$THEME_DIR/hyprland.conf" << EOF
# Hyprland Colors
# Generated by Omarchy Theme Editor

\$background = ${background//#/}
\$foreground = ${foreground//#/}
\$color0 = ${color0//#/}
\$color1 = ${color1//#/}
\$color2 = ${color2//#/}
\$color3 = ${color3//#/}
\$color4 = ${color4//#/}
\$color5 = ${color5//#/}
\$color6 = ${color6//#/}
\$color7 = ${color7//#/}
\$color8 = ${color8//#/}
\$color9 = ${color9//#/}
\$color10 = ${color10//#/}
\$color11 = ${color11//#/}
\$color12 = ${color12//#/}
\$color13 = ${color13//#/}
\$color14 = ${color14//#/}
\$color15 = ${color15//#/}

general {
    col.active_border = rgb(\$color4) rgb(\$color5) 45deg
    col.inactive_border = rgb(\$color8)
}

decoration {
    col.shadow = rgba(\$color0aa)
}
EOF

# 3. Generate Waybar CSS
cat > "$THEME_DIR/waybar.css" << EOF
/* Waybar Colors */
/* Generated by Omarchy Theme Editor */

@define-color background $background;
@define-color foreground $foreground;
@define-color color0 $color0;
@define-color color1 $color1;
@define-color color2 $color2;
@define-color color3 $color3;
@define-color color4 $color4;
@define-color color5 $color5;
@define-color color6 $color6;
@define-color color7 $color7;
@define-color color8 $color8;
@define-color color9 $color9;
@define-color color10 $color10;
@define-color color11 $color11;
@define-color color12 $color12;
@define-color color13 $color13;
@define-color color14 $color14;
@define-color color15 $color15;

* {
    background: @background;
    color: @foreground;
}

#workspaces button.active {
    background: @color4;
    color: @background;
}

#workspaces button.urgent {
    background: @color1;
    color: @background;
}

#battery.warning {
    color: @color3;
}

#battery.critical {
    color: @color1;
}
EOF

# 4. Generate Fuzzel config
cat > "$THEME_DIR/fuzzel.ini" << EOF
# Fuzzel Colors
# Generated by Omarchy Theme Editor

[colors]
background=${background}ee
text=${foreground}ff
match=${color4}ff
selection=${color4}44
selection-text=${foreground}ff
border=${color4}ff
EOF

# 5. Generate Kitty config (bonus)
cat > "$THEME_DIR/kitty.conf" << EOF
# Kitty Colors
# Generated by Omarchy Theme Editor

background $background
foreground $foreground

color0  $color0
color1  $color1
color2  $color2
color3  $color3
color4  $color4
color5  $color5
color6  $color6
color7  $color7
color8  $color8
color9  $color9
color10 $color10
color11 $color11
color12 $color12
color13 $color13
color14 $color14
color15 $color15
EOF

# 6. Create README
cat > "$THEME_DIR/README.md" << EOF
# $(jq -r '.name // "Custom Theme"' "$THEME_DIR/theme.json" 2>/dev/null || echo "Custom Theme")

**Author:** $(jq -r '.author // "Anonymous"' "$THEME_DIR/theme.json" 2>/dev/null || echo "Anonymous")
**Version:** $(jq -r '.version // "1.0.0"' "$THEME_DIR/theme.json" 2>/dev/null || echo "1.0.0")
**Created:** $(date +%Y-%m-%d)

## Description

$(jq -r '.description // "A custom Omarchy theme"' "$THEME_DIR/theme.json" 2>/dev/null || echo "A custom Omarchy theme")

## Color Palette

| Color | HEX Value |
|-------|-----------|
| Background | $background |
| Foreground | $foreground |
| Black | $color0 |
| Red | $color1 |
| Green | $color2 |
| Yellow | $color3 |
| Blue | $color4 |
| Magenta | $color5 |
| Cyan | $color6 |
| White | $color7 |
| Bright Black | $color8 |
| Bright Red | $color9 |
| Bright Green | $color10 |
| Bright Yellow | $color11 |
| Bright Blue | $color12 |
| Bright Magenta | $color13 |
| Bright Cyan | $color14 |
| Bright White | $color15 |

## Installation

\`\`\`bash
# Extract theme to Omarchy themes directory
cp -r . ~/.local/share/omarchy/themes/$(basename "$THEME_DIR")

# Link to active themes
ln -sf ~/.local/share/omarchy/themes/$(basename "$THEME_DIR") ~/.config/omarchy/themes/$(basename "$THEME_DIR")

# Apply theme
omarchy-theme-set $(basename "$THEME_DIR")
\`\`\`

---
*Generated with Omarchy Theme Editor*
EOF

# Generate GTK themes
if [ -f "$COLORS_FILE" ]; then
    ~/.config/rice-menu/themes/gtk/generate-gtk3.sh "$THEME_DIR" 2>/dev/null || true
    ~/.config/rice-menu/themes/gtk/generate-gtk4.sh "$THEME_DIR" 2>/dev/null || true
fi

notify-send "✓ Complete" "All configuration files generated successfully (including GTK themes)"
